
@startuml

title: Pieza Negra en (3,4) puede comer a Pieza Blanca en (4,3)


":TestCase" -> ":Jugador": moverA(piezaNegra, p)
":Jugador" -> ":Tablero": moverA(piezaNegra, p)
":Tablero" -> ":Tablero": contenidoDe(p)
":Tablero" -> "piezaEnPosicion:Pieza": mismoColor(piezaNegra)
return [true]
":Tablero" -> ":Tablero": colocarEn(piezaNegra, p)
":Tablero" --> ":Jugador": true
":Jugador" --> ":TestCase": true
@enduml