@startuml ModeloInicial-V0.3

Class ALTEGO{

}

Class Tablero{
    -buscarPais(pais)
    +atacarConA(jugador: Jugador, paisMio: String, pasiEnemigo: String)
    +agregarFichas(jugador: Jugador, pais: String, num: Integer)
}

Class Continente{
    +ocupadoPorJugador(jugador: Jugador)
    +cantidadDePaisesOcupadosPor(jugador: Jugador)
}

Class Jugador{
    -tipoEjercito: Ejercito
    +atacarConA(paisMio: String,paisEnemigo: String)
    +turnoAgregar()
    +turnoAtacar()
}

Class Pais{
    -jugador: Jugador
    -adyacentes: Dictionary
    -actualizarJugador(paisAtacante: Pais)
    +esAdyacente(pais: Pais)
    +getJugador(): Jugador
    +tirarDadosAtacar():
    +tirarDadosDefender():
    +esDelJugador(jugador: Jugador): boolean
    +agregarFichas(jugador: Jugador, num: Integer)
    +perderFichas(num: Integer)
    +perderFichas(num: Integer, paisAtacante: Pais):
    +pasarFichas(pais)
    +ponerFichasDe(num: Integer,jugador)
}

Class Ejercito{
    -cantidadFichas: Int
    +tirarDadosAtacar():
    +tirarDadosDefender():
    +agregarFichas(num: Int)
    +perderFichas(num: Integer): Integer
    +pasarFichasFichasADe(pais: Pais, jugador: Jugador)
}


Class Batalla{
    +atacarConA(jugador: Jugador, paisMio: Pais, paisEnemigo: Pais):
}

Class TarjetaPais{
    - simbolo
}

Class TarjetaObjetivo{}

ALTEGO --> Tablero
ALTEGO --> "2..6"Jugador
Jugador  -left-> Tablero
Tablero "1"-->"50" Pais
Tablero "1"-->"6" Continente
Tablero ..> Batalla
Batalla .left.> Pais
Continente --right-->"n..m" Pais
Pais "1"-->"1" Ejercito
Jugador --> TarjetaObjetivo
TarjetaObjetivo ..> Tablero
TarjetaPais --> Pais

@enduml