@startuml ModeloInicial

note left Jugador
le toca la carta pais
end note
Jugador -> Jugador: crearEjercito(numTropas)
Jugador -> Tablero: agregarTropasA(ejercito, pais)
Tablero -> Tablero: buscarPais(pais)
Tablero ->Pais: agregarTropas(EjercitoMagenta)
Pais -> EjercitoSinTipo: agregarTropas(EjercitoMagenta)
note right EjercitoSinTipo
agregarTropas
    return ejercito;
end note
EjercitoSinTipo --> Pais: EjercitoMagenta


@enduml