@startuml DiagramaDeSecuenciaUnPaisAtacaAOtro

Participant Jugador
Participant Tablero
Participant Batalla
Participant Pais as "paisMio: Pais"
Participant PaisEnemigo as "paisEnemigo: Pais"
Participant Ejercito as "ejercito: Ejercito"
Participant FichaEnemigo as "ejercitoEnemigo: Ejercito"

activate Tablero
Jugador->Tablero: atacarConA(colorJugador, paisMio, paisEnemigo)
Tablero -> Tablero: buscarPais(PaisMio)
activate Tablero
Tablero --> Tablero: paisMio
deactivate Tablero
Tablero -> Tablero: buscarPais(paisEnemigo)
activate Tablero
Tablero --> Tablero: paisEnemigo
deactivate Tablero
Tablero -> Batalla: atacarConA(colorJugador, paisMio, paisEnemigo)
activate Batalla
Batalla -> Batalla: esAtaqueValido()
activate Batalla
deactivate Tablero
Batalla -> Pais: esDeJugador(colorJugador)
activate Pais
Pais --> Batalla: true: Boolean
deactivate Pais
Batalla -> Pais: esAdyacente(paisEnemigo)
activate Pais
Pais --> Batalla: true: Boolean
deactivate Pais
Batalla -> PaisEnemigo: esDeJugador(colorJugador)
activate PaisEnemigo
PaisEnemigo --> Batalla: false: Boolean
deactivate PaisEnemigo
Batalla --> Batalla: true:Boolean
deactivate Batalla
Batalla -> Pais: tirarDadosAtacar()
Pais -> Ejercito: tirarDadosAtacar()
Ejercito --> Pais:
Pais --> Batalla
Batalla -> PaisEnemigo: tirarDadosDefender()
PaisEnemigo -> EjercitoEnemigo: tirarDadosDefender()
EjercitoEnemigo --> PaisEnemigo
PaisEnemigo --> Batalla
Batalla -> Pais: pederFichas(colorJugador, num)
Batalla -> PaisEnemigo: perderFichas(colorJugador, num)

@enduml