@startuml
'https://plantuml.com/sequence-diagram


actor Interfaz
participant Turnos as ":Turnos"
participant Ronda as "tipoRonda:RondaColocacion"
participant Teg as ":Teg"
participant MazoTeg as ":CartasPaisTeg"
participant Jugador as ":Jugador"

Interfaz -> Turnos: darCartaPais()

Turnos -> Ronda: darCartaPais(Teg teg)
activate Ronda
Ronda -> Teg: darCartaPaisA(String jugador)
activate Teg
Teg -> MazoTeg: darCartaA(Jugador j)
activate MazoTeg
MazoTeg -> Jugador: darCartaA(Jugador j)
activate Jugador
note over Jugador
 Se comprueba que el jugador
 haya capturado un pais.
 En este caso no capturo
end note


'returns
Jugador --> MazoTeg: false: Boolean
deactivate Jugador
MazoTeg --> Teg: false: Boolean
deactivate MazoTeg
Teg --> Ronda: false: Boolean
deactivate Teg
Ronda --> Turnos: false: Boolean
deactivate
Turnos --> Interfaz: false: Boolean


@enduml